local handler = require("event_handler")
handler.add_lib(require("script.main"):export())
handler.add_lib(require("script.revlab"):export())
handler.add_lib(require("script.explain"):export())
require("informatron")