require("prototypes.objects.rod-1")
require("prototypes.objects.rod-2")
require("prototypes.objects.han-1")
require("prototypes.objects.han-2")
require("prototypes.objects.arty-1")
require("prototypes.objects.arty-2")
require("prototypes.objects.arty-tool")

require("prototypes.damage")
require("prototypes.fx")

require("prototypes.tech.main")
require("prototypes.tech.catch-prob")
require("prototypes.tech.catch-energy")
require("prototypes.tech.arty-range")
require("prototypes.tech.arty-lvl")