data:extend{
    -- Logistics
    {
        type = "bool-setting",
        name = "af-prod-enable-belts",
        setting_type = "startup",
        default_value = true,
        order = "a-1",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-inserters",
        setting_type = "startup",
        default_value = true,
        order = "a-2",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-containers",
        setting_type = "startup",
        default_value = true,
        order = "a-3",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-robots",
        setting_type = "startup",
        default_value = true,
        order = "a-4",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-rails",
        setting_type = "startup",
        default_value = true,
        order = "a-5",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-rail-stops+signals",
        setting_type = "startup",
        default_value = true,
        order = "a-6",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-trains",
        setting_type = "startup",
        default_value = true,
        order = "a-7",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-vehicles",
        setting_type = "startup",
        default_value = false,
        order = "a-8",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-fluid-sys",
        setting_type = "startup",
        default_value = true,
        order = "a-9",
    },
    -- Buildings
    {
        type = "bool-setting",
        name = "af-prod-enable-miners",
        setting_type = "startup",
        default_value = false,
        order = "b-1",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-assemblers",
        setting_type = "startup",
        default_value = false,
        order = "b-2",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-roboports",
        setting_type = "startup",
        default_value = false,
        order = "b-3",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-solar+acc",
        setting_type = "startup",
        default_value = true,
        order = "b-4",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-boiler+gen",
        setting_type = "startup",
        default_value = false,
        order = "b-5",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-turrets",
        setting_type = "startup",
        default_value = true,
        order = "b-6",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-walls",
        setting_type = "startup",
        default_value = true,
        order = "b-7",
    },
    -- Misc
    {
        type = "bool-setting",
        name = "af-prod-enable-modules",
        setting_type = "startup",
        default_value = false,
        order = "c-1",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-poles",
        setting_type = "startup",
        default_value = true,
        order = "c-2",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-combinators",
        setting_type = "startup",
        default_value = false,
        order = "c-3",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-satellites",
        setting_type = "startup",
        default_value = false,
        order = "c-4",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-tiles",
        setting_type = "startup",
        default_value = true,
        order = "c-5",
    },
    -- Armor & Ammo
    {
        type = "bool-setting",
        name = "af-prod-enable-armor",
        setting_type = "startup",
        default_value = true,
        order = "d-1",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-equipment",
        setting_type = "startup",
        default_value = true,
        order = "d-2",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-guns",
        setting_type = "startup",
        default_value = false,
        order = "d-3",
    },
    {
        type = "bool-setting",
        name = "af-prod-enable-ammo",
        setting_type = "startup",
        default_value = true,
        order = "d-4",
    },
}